apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1-deployment
  labels:
    app: web1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - name: web1
        image: scramby/scram:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web1-service
spec:
  type: NodePort
  selector:
    app: web1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
